      // Generated by the protocol buffer compiler.  DO NOT EDIT!
      using System;
      using System.Linq;
      using System.Collections.Generic;
      using System.Collections.ObjectModel;
using Master;
namespace Game
{
	public partial class Card
	{
	}

}
