// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: master.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using System.Collections.Generic;
using pb = global::Google.ProtocolBuffers;
using scg = global::System.Collections.Generic;
namespace Master {

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  public static partial class Master {

  }
  #region Enums
  public enum SettingType {
    Integer = 0,
    String = 1,
    Float = 2,
  }

  public enum PlatformType {
    Windows = 0,
    Switch = 1,
    Ps4 = 2,
    Wsa = 3,
    Steam = 4,
  }

  #endregion

  #region Messages
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  public sealed partial class PbxHeader : pb.Message {
    public PbxHeader() { }
    public static PbxHeader CreateInstance() { var obj = new PbxHeader(); obj.Finish(); return obj; }
    public static PbxHeader CreateEmpty() { return new PbxHeader(); }
    private static readonly PbxHeader defaultInstance = new PbxHeader();
    public static PbxHeader DefaultInstance {
      get { return defaultInstance; }
    }

    #region Nested types
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public static partial class Types {
      [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
      public sealed partial class IntIndexEntry : pb.Message {
        public IntIndexEntry() { }
        public static IntIndexEntry CreateInstance() { var obj = new IntIndexEntry(); obj.Finish(); return obj; }
        public static IntIndexEntry CreateEmpty() { return new IntIndexEntry(); }
        private static readonly IntIndexEntry defaultInstance = new IntIndexEntry();
        public static IntIndexEntry DefaultInstance {
          get { return defaultInstance; }
        }

        public int Key;

        public int Value;

        #region Lite runtime methods
        #endregion

        public override void WriteTo(pb::CodedOutputStream output) {
          CalcSerializedSize();
          if (Key != 0) {
            output.WriteInt32(1, Key);
          }
          if (Value != 0) {
            output.WriteInt32(2, Value);
          }
        }

        public override int SerializedSize {
          get {
            return CalcSerializedSize();
          }
        }

        private int CalcSerializedSize() {
          int size = 0;
          if (Key != 0) {
            size += pb::CodedOutputStream.ComputeInt32Size(1, Key);
          }
          if (Value != 0) {
            size += pb::CodedOutputStream.ComputeInt32Size(2, Value);
          }
          return size;
        }
        public static IntIndexEntry ParseFrom(byte[] data) {
          var mes = CreateInstance(); mes.MergeFrom(data); return mes;
        }
        public static IntIndexEntry ParseFrom(global::System.IO.Stream input) {
          var mes = CreateInstance(); mes.MergeFrom(input); return mes;
        }
        public static IntIndexEntry ParseFrom(pb::CodedInputStream input) {
          var mes = CreateInstance(); mes.MergeFrom(input); return mes;
        }
        public override void MergeFrom(pb::CodedInputStream input) {
          uint tag;
          while (input.ReadTag(out tag)) {
            switch (tag) {
              case 0: {
                throw pb::InvalidProtocolBufferException.InvalidTag();
              }
              default: {
                if (pb::WireFormat.IsEndGroupTag(tag)) {
                  return;
                }
                break;
              }
              case 8: {
                input.ReadInt32(ref this.Key);
                break;
              }
              case 16: {
                input.ReadInt32(ref this.Value);
                break;
              }
            }
          }
        }

        public override void Init() {
        }
        public override void Finish() {
        }
      }

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
      public sealed partial class StringIndexEntry : pb.Message {
        public StringIndexEntry() { }
        public static StringIndexEntry CreateInstance() { var obj = new StringIndexEntry(); obj.Finish(); return obj; }
        public static StringIndexEntry CreateEmpty() { return new StringIndexEntry(); }
        private static readonly StringIndexEntry defaultInstance = new StringIndexEntry();
        public static StringIndexEntry DefaultInstance {
          get { return defaultInstance; }
        }

        public string Key = "";

        public int Value;

        #region Lite runtime methods
        #endregion

        public override void WriteTo(pb::CodedOutputStream output) {
          CalcSerializedSize();
          if (Key != "") {
            output.WriteString(1, Key);
          }
          if (Value != 0) {
            output.WriteInt32(2, Value);
          }
        }

        public override int SerializedSize {
          get {
            return CalcSerializedSize();
          }
        }

        private int CalcSerializedSize() {
          int size = 0;
          if (Key != "") {
            size += pb::CodedOutputStream.ComputeStringSize(1, Key);
          }
          if (Value != 0) {
            size += pb::CodedOutputStream.ComputeInt32Size(2, Value);
          }
          return size;
        }
        public static StringIndexEntry ParseFrom(byte[] data) {
          var mes = CreateInstance(); mes.MergeFrom(data); return mes;
        }
        public static StringIndexEntry ParseFrom(global::System.IO.Stream input) {
          var mes = CreateInstance(); mes.MergeFrom(input); return mes;
        }
        public static StringIndexEntry ParseFrom(pb::CodedInputStream input) {
          var mes = CreateInstance(); mes.MergeFrom(input); return mes;
        }
        public override void MergeFrom(pb::CodedInputStream input) {
          uint tag;
          while (input.ReadTag(out tag)) {
            switch (tag) {
              case 0: {
                throw pb::InvalidProtocolBufferException.InvalidTag();
              }
              default: {
                if (pb::WireFormat.IsEndGroupTag(tag)) {
                  return;
                }
                break;
              }
              case 10: {
                input.ReadString(ref this.Key);
                break;
              }
              case 16: {
                input.ReadInt32(ref this.Value);
                break;
              }
            }
          }
        }

        public override void Init() {
        }
        public override void Finish() {
        }
      }

    }
    #endregion

    public List<global::Master.PbxHeader.Types.IntIndexEntry> IntIndex = new List<global::Master.PbxHeader.Types.IntIndexEntry>();

    public List<global::Master.PbxHeader.Types.StringIndexEntry> StringIndex = new List<global::Master.PbxHeader.Types.StringIndexEntry>();

    #region Lite runtime methods
    #endregion

    public override void WriteTo(pb::CodedOutputStream output) {
      CalcSerializedSize();
      if (IntIndex != null && IntIndex.Count > 0) {
        output.WriteMessageArray(1, IntIndex);
      }
      if (StringIndex != null && StringIndex.Count > 0) {
        output.WriteMessageArray(2, StringIndex);
      }
    }

    public override int SerializedSize {
      get {
        return CalcSerializedSize();
      }
    }

    private int CalcSerializedSize() {
      int size = 0;
      if( IntIndex != null ) {
        foreach (global::Master.PbxHeader.Types.IntIndexEntry element in IntIndex) {
          size += pb::CodedOutputStream.ComputeMessageSize(1, element);
        }
      }
      if( StringIndex != null ) {
        foreach (global::Master.PbxHeader.Types.StringIndexEntry element in StringIndex) {
          size += pb::CodedOutputStream.ComputeMessageSize(2, element);
        }
      }
      return size;
    }
    public static PbxHeader ParseFrom(byte[] data) {
      var mes = CreateInstance(); mes.MergeFrom(data); return mes;
    }
    public static PbxHeader ParseFrom(global::System.IO.Stream input) {
      var mes = CreateInstance(); mes.MergeFrom(input); return mes;
    }
    public static PbxHeader ParseFrom(pb::CodedInputStream input) {
      var mes = CreateInstance(); mes.MergeFrom(input); return mes;
    }
    public override void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while (input.ReadTag(out tag)) {
        switch (tag) {
          case 0: {
            throw pb::InvalidProtocolBufferException.InvalidTag();
          }
          default: {
            if (pb::WireFormat.IsEndGroupTag(tag)) {
              return;
            }
            break;
          }
          case 10: {
            input.ReadMessageArray(tag, this.IntIndex, global::Master.PbxHeader.Types.IntIndexEntry.CreateEmpty);
            break;
          }
          case 18: {
            input.ReadMessageArray(tag, this.StringIndex, global::Master.PbxHeader.Types.StringIndexEntry.CreateEmpty);
            break;
          }
        }
      }
    }

    public override void Init() {
    }
    public override void Finish() {
    if( IntIndex == null ){
      IntIndex = new List<global::Master.PbxHeader.Types.IntIndexEntry>();
    }
    if( StringIndex == null ){
      StringIndex = new List<global::Master.PbxHeader.Types.StringIndexEntry>();
    }
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  public sealed partial class I18nMessage : pb.Message {
    public I18nMessage() { }
    public static I18nMessage CreateInstance() { var obj = new I18nMessage(); obj.Finish(); return obj; }
    public static I18nMessage CreateEmpty() { return new I18nMessage(); }
    private static readonly I18nMessage defaultInstance = new I18nMessage();
    public static I18nMessage DefaultInstance {
      get { return defaultInstance; }
    }

    public string Id = "";

    public string Text = "";

    public string Tag = "";

    public string Variant = "";

    #region Lite runtime methods
    #endregion

    public override void WriteTo(pb::CodedOutputStream output) {
      CalcSerializedSize();
      if (Id != "") {
        output.WriteString(1, Id);
      }
      if (Text != "") {
        output.WriteString(2, Text);
      }
      if (Tag != "") {
        output.WriteString(3, Tag);
      }
      if (Variant != "") {
        output.WriteString(4, Variant);
      }
    }

    public override int SerializedSize {
      get {
        return CalcSerializedSize();
      }
    }

    private int CalcSerializedSize() {
      int size = 0;
      if (Id != "") {
        size += pb::CodedOutputStream.ComputeStringSize(1, Id);
      }
      if (Text != "") {
        size += pb::CodedOutputStream.ComputeStringSize(2, Text);
      }
      if (Tag != "") {
        size += pb::CodedOutputStream.ComputeStringSize(3, Tag);
      }
      if (Variant != "") {
        size += pb::CodedOutputStream.ComputeStringSize(4, Variant);
      }
      return size;
    }
    public static I18nMessage ParseFrom(byte[] data) {
      var mes = CreateInstance(); mes.MergeFrom(data); return mes;
    }
    public static I18nMessage ParseFrom(global::System.IO.Stream input) {
      var mes = CreateInstance(); mes.MergeFrom(input); return mes;
    }
    public static I18nMessage ParseFrom(pb::CodedInputStream input) {
      var mes = CreateInstance(); mes.MergeFrom(input); return mes;
    }
    public override void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while (input.ReadTag(out tag)) {
        switch (tag) {
          case 0: {
            throw pb::InvalidProtocolBufferException.InvalidTag();
          }
          default: {
            if (pb::WireFormat.IsEndGroupTag(tag)) {
              return;
            }
            break;
          }
          case 10: {
            input.ReadString(ref this.Id);
            break;
          }
          case 18: {
            input.ReadString(ref this.Text);
            break;
          }
          case 26: {
            input.ReadString(ref this.Tag);
            break;
          }
          case 34: {
            input.ReadString(ref this.Variant);
            break;
          }
        }
      }
    }

    public override void Init() {
    }
    public override void Finish() {
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  public sealed partial class MessageFusion : pb.Message {
    public MessageFusion() { }
    public static MessageFusion CreateInstance() { var obj = new MessageFusion(); obj.Finish(); return obj; }
    public static MessageFusion CreateEmpty() { return new MessageFusion(); }
    private static readonly MessageFusion defaultInstance = new MessageFusion();
    public static MessageFusion DefaultInstance {
      get { return defaultInstance; }
    }

    public string Id1 = "";

    public string Id2 = "";

    public string Text = "";

    #region Lite runtime methods
    #endregion

    public override void WriteTo(pb::CodedOutputStream output) {
      CalcSerializedSize();
      if (Id1 != "") {
        output.WriteString(1, Id1);
      }
      if (Id2 != "") {
        output.WriteString(2, Id2);
      }
      if (Text != "") {
        output.WriteString(3, Text);
      }
    }

    public override int SerializedSize {
      get {
        return CalcSerializedSize();
      }
    }

    private int CalcSerializedSize() {
      int size = 0;
      if (Id1 != "") {
        size += pb::CodedOutputStream.ComputeStringSize(1, Id1);
      }
      if (Id2 != "") {
        size += pb::CodedOutputStream.ComputeStringSize(2, Id2);
      }
      if (Text != "") {
        size += pb::CodedOutputStream.ComputeStringSize(3, Text);
      }
      return size;
    }
    public static MessageFusion ParseFrom(byte[] data) {
      var mes = CreateInstance(); mes.MergeFrom(data); return mes;
    }
    public static MessageFusion ParseFrom(global::System.IO.Stream input) {
      var mes = CreateInstance(); mes.MergeFrom(input); return mes;
    }
    public static MessageFusion ParseFrom(pb::CodedInputStream input) {
      var mes = CreateInstance(); mes.MergeFrom(input); return mes;
    }
    public override void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while (input.ReadTag(out tag)) {
        switch (tag) {
          case 0: {
            throw pb::InvalidProtocolBufferException.InvalidTag();
          }
          default: {
            if (pb::WireFormat.IsEndGroupTag(tag)) {
              return;
            }
            break;
          }
          case 10: {
            input.ReadString(ref this.Id1);
            break;
          }
          case 18: {
            input.ReadString(ref this.Id2);
            break;
          }
          case 26: {
            input.ReadString(ref this.Text);
            break;
          }
        }
      }
    }

    public override void Init() {
    }
    public override void Finish() {
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  public sealed partial class ConfigInfo : pb.Message {
    public ConfigInfo() { }
    public static ConfigInfo CreateInstance() { var obj = new ConfigInfo(); obj.Finish(); return obj; }
    public static ConfigInfo CreateEmpty() { return new ConfigInfo(); }
    private static readonly ConfigInfo defaultInstance = new ConfigInfo();
    public static ConfigInfo DefaultInstance {
      get { return defaultInstance; }
    }

    public string Id = "";

    public string Value = "";

    public global::Master.SettingType Type = global::Master.SettingType.Integer;

    public string Spec = "";

    #region Lite runtime methods
    #endregion

    public override void WriteTo(pb::CodedOutputStream output) {
      CalcSerializedSize();
      if (Id != "") {
        output.WriteString(1, Id);
      }
      if (Value != "") {
        output.WriteString(2, Value);
      }
      if (Type != global::Master.SettingType.Integer) {
        output.WriteEnum(3, (int) Type, Type);
      }
      if (Spec != "") {
        output.WriteString(4, Spec);
      }
    }

    public override int SerializedSize {
      get {
        return CalcSerializedSize();
      }
    }

    private int CalcSerializedSize() {
      int size = 0;
      if (Id != "") {
        size += pb::CodedOutputStream.ComputeStringSize(1, Id);
      }
      if (Value != "") {
        size += pb::CodedOutputStream.ComputeStringSize(2, Value);
      }
      if (Type != global::Master.SettingType.Integer) {
        size += pb::CodedOutputStream.ComputeEnumSize(3, (int) Type);
      }
      if (Spec != "") {
        size += pb::CodedOutputStream.ComputeStringSize(4, Spec);
      }
      return size;
    }
    public static ConfigInfo ParseFrom(byte[] data) {
      var mes = CreateInstance(); mes.MergeFrom(data); return mes;
    }
    public static ConfigInfo ParseFrom(global::System.IO.Stream input) {
      var mes = CreateInstance(); mes.MergeFrom(input); return mes;
    }
    public static ConfigInfo ParseFrom(pb::CodedInputStream input) {
      var mes = CreateInstance(); mes.MergeFrom(input); return mes;
    }
    public override void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while (input.ReadTag(out tag)) {
        switch (tag) {
          case 0: {
            throw pb::InvalidProtocolBufferException.InvalidTag();
          }
          default: {
            if (pb::WireFormat.IsEndGroupTag(tag)) {
              return;
            }
            break;
          }
          case 10: {
            input.ReadString(ref this.Id);
            break;
          }
          case 18: {
            input.ReadString(ref this.Value);
            break;
          }
          case 24: {
            input.ReadEnum(ref this.Type);
            break;
          }
          case 34: {
            input.ReadString(ref this.Spec);
            break;
          }
        }
      }
    }

    public override void Init() {
    }
    public override void Finish() {
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  public sealed partial class CardTemplate : pb.Message {
    public CardTemplate() { }
    public static CardTemplate CreateInstance() { var obj = new CardTemplate(); obj.Finish(); return obj; }
    public static CardTemplate CreateEmpty() { return new CardTemplate(); }
    private static readonly CardTemplate defaultInstance = new CardTemplate();
    public static CardTemplate DefaultInstance {
      get { return defaultInstance; }
    }

    public int Id;

    public string Name = "";

    #region Lite runtime methods
    #endregion

    public override void WriteTo(pb::CodedOutputStream output) {
      CalcSerializedSize();
      if (Id != 0) {
        output.WriteInt32(1, Id);
      }
      if (Name != "") {
        output.WriteString(2, Name);
      }
    }

    public override int SerializedSize {
      get {
        return CalcSerializedSize();
      }
    }

    private int CalcSerializedSize() {
      int size = 0;
      if (Id != 0) {
        size += pb::CodedOutputStream.ComputeInt32Size(1, Id);
      }
      if (Name != "") {
        size += pb::CodedOutputStream.ComputeStringSize(2, Name);
      }
      return size;
    }
    public static CardTemplate ParseFrom(byte[] data) {
      var mes = CreateInstance(); mes.MergeFrom(data); return mes;
    }
    public static CardTemplate ParseFrom(global::System.IO.Stream input) {
      var mes = CreateInstance(); mes.MergeFrom(input); return mes;
    }
    public static CardTemplate ParseFrom(pb::CodedInputStream input) {
      var mes = CreateInstance(); mes.MergeFrom(input); return mes;
    }
    public override void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while (input.ReadTag(out tag)) {
        switch (tag) {
          case 0: {
            throw pb::InvalidProtocolBufferException.InvalidTag();
          }
          default: {
            if (pb::WireFormat.IsEndGroupTag(tag)) {
              return;
            }
            break;
          }
          case 8: {
            input.ReadInt32(ref this.Id);
            break;
          }
          case 18: {
            input.ReadString(ref this.Name);
            break;
          }
        }
      }
    }

    public override void Init() {
    }
    public override void Finish() {
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  public sealed partial class DebugMenuInfo : pb.Message {
    public DebugMenuInfo() { }
    public static DebugMenuInfo CreateInstance() { var obj = new DebugMenuInfo(); obj.Finish(); return obj; }
    public static DebugMenuInfo CreateEmpty() { return new DebugMenuInfo(); }
    private static readonly DebugMenuInfo defaultInstance = new DebugMenuInfo();
    public static DebugMenuInfo DefaultInstance {
      get { return defaultInstance; }
    }

    public string Name = "";

    public string Action = "";

    public string Shortcut = "";

    public List<global::Master.DebugMenuInfo> Children = new List<global::Master.DebugMenuInfo>();

    #region Lite runtime methods
    #endregion

    public override void WriteTo(pb::CodedOutputStream output) {
      CalcSerializedSize();
      if (Name != "") {
        output.WriteString(1, Name);
      }
      if (Action != "") {
        output.WriteString(2, Action);
      }
      if (Children != null && Children.Count > 0) {
        output.WriteMessageArray(3, Children);
      }
      if (Shortcut != "") {
        output.WriteString(4, Shortcut);
      }
    }

    public override int SerializedSize {
      get {
        return CalcSerializedSize();
      }
    }

    private int CalcSerializedSize() {
      int size = 0;
      if (Name != "") {
        size += pb::CodedOutputStream.ComputeStringSize(1, Name);
      }
      if (Action != "") {
        size += pb::CodedOutputStream.ComputeStringSize(2, Action);
      }
      if (Shortcut != "") {
        size += pb::CodedOutputStream.ComputeStringSize(4, Shortcut);
      }
      if( Children != null ) {
        foreach (global::Master.DebugMenuInfo element in Children) {
          size += pb::CodedOutputStream.ComputeMessageSize(3, element);
        }
      }
      return size;
    }
    public static DebugMenuInfo ParseFrom(byte[] data) {
      var mes = CreateInstance(); mes.MergeFrom(data); return mes;
    }
    public static DebugMenuInfo ParseFrom(global::System.IO.Stream input) {
      var mes = CreateInstance(); mes.MergeFrom(input); return mes;
    }
    public static DebugMenuInfo ParseFrom(pb::CodedInputStream input) {
      var mes = CreateInstance(); mes.MergeFrom(input); return mes;
    }
    public override void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while (input.ReadTag(out tag)) {
        switch (tag) {
          case 0: {
            throw pb::InvalidProtocolBufferException.InvalidTag();
          }
          default: {
            if (pb::WireFormat.IsEndGroupTag(tag)) {
              return;
            }
            break;
          }
          case 10: {
            input.ReadString(ref this.Name);
            break;
          }
          case 18: {
            input.ReadString(ref this.Action);
            break;
          }
          case 26: {
            input.ReadMessageArray(tag, this.Children, global::Master.DebugMenuInfo.CreateEmpty);
            break;
          }
          case 34: {
            input.ReadString(ref this.Shortcut);
            break;
          }
        }
      }
    }

    public override void Init() {
    }
    public override void Finish() {
    if( Children == null ){
      Children = new List<global::Master.DebugMenuInfo>();
    }
    }
  }

  #endregion

}

#endregion Designer generated code
