# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: game_log.proto

require 'google/protobuf'

require 'master_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "GameLog.Hoge" do
    optional :id, :int32, 1
  end
  add_message "GameLog.ShutdownRequest" do
  end
  add_message "GameLog.AckResponseRequest" do
  end
  add_message "GameLog.PlayCardRequest" do
    optional :card_id, :int32, 1
  end
  add_message "GameLog.DrawCardRequest" do
  end
  add_message "GameLog.CardPlayed" do
  end
end

module GameLog
  Hoge = Google::Protobuf::DescriptorPool.generated_pool.lookup("GameLog.Hoge").msgclass
  ShutdownRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("GameLog.ShutdownRequest").msgclass
  AckResponseRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("GameLog.AckResponseRequest").msgclass
  PlayCardRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("GameLog.PlayCardRequest").msgclass
  DrawCardRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("GameLog.DrawCardRequest").msgclass
  CardPlayed = Google::Protobuf::DescriptorPool.generated_pool.lookup("GameLog.CardPlayed").msgclass
end
