# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: game_log.proto

require 'google/protobuf'

require 'master_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
end

module GameLog
end
