# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: master.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "Master.PbxHeader" do
    map :int_index, :int32, :int32, 1
    map :string_index, :string, :int32, 2
  end
  add_message "Master.I18nMessage" do
    optional :id, :string, 1
    optional :text, :string, 2
    optional :tag, :string, 3
    optional :variant, :string, 4
  end
  add_message "Master.MessageFusion" do
    optional :id1, :string, 1
    optional :id2, :string, 2
    optional :text, :string, 3
  end
  add_message "Master.ConfigInfo" do
    optional :id, :string, 1
    optional :value, :string, 2
    optional :type, :enum, 3, "Master.SettingType"
    optional :spec, :string, 4
  end
  add_message "Master.DebugMenuInfo" do
    optional :name, :string, 1
    optional :action, :string, 2
    optional :shortcut, :string, 4
    repeated :children, :message, 3, "Master.DebugMenuInfo"
  end
  add_enum "Master.SettingType" do
    value :Integer, 0
    value :String, 1
    value :Float, 2
  end
end

module Master
  PbxHeader = Google::Protobuf::DescriptorPool.generated_pool.lookup("Master.PbxHeader").msgclass
  I18nMessage = Google::Protobuf::DescriptorPool.generated_pool.lookup("Master.I18nMessage").msgclass
  MessageFusion = Google::Protobuf::DescriptorPool.generated_pool.lookup("Master.MessageFusion").msgclass
  ConfigInfo = Google::Protobuf::DescriptorPool.generated_pool.lookup("Master.ConfigInfo").msgclass
  DebugMenuInfo = Google::Protobuf::DescriptorPool.generated_pool.lookup("Master.DebugMenuInfo").msgclass
  SettingType = Google::Protobuf::DescriptorPool.generated_pool.lookup("Master.SettingType").enummodule
end
