// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: game_log.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using System.Collections.Generic;
using pb = global::Google.ProtocolBuffers;
using scg = global::System.Collections.Generic;
namespace GameLog {

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  public static partial class GameLog {

  }
}

#endregion Designer generated code
